# Generated by Django 4.1.5 on 2023-01-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0003_alter_response_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='upload',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
