# Generated by Django 4.1.5 on 2023-01-18 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BulletinBoard', '0005_alter_advert_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='editTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
